export const GET_ERRORS = "GET_ERRORS";
export const GET_CLIENTS = "GET_CLIENTS";
export const GET_CLIENT = "GET_CLIENT";
export const DELETE_CLIENT = "DELETE_CLIENT";

export const GET_BACKLOG_CLIENT = "GET_BACKLOG_CLIENT";
export const GET_TOOTH = "GET_TOOTH";
export const DELETE_TOOTH = "DELETE_TOOTH";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const GET_XRAYPHOTOS = "GET_XRAYPHOTOS";
export const GET_XRAYPHOTO = "GET_XRAYPHOTO";
export const DELETE_XRAYPHOTO = "DELETE_XRAYPHOTO";
